server:
  port: 66

spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource    # 数据源的类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql的数据库驱动类名称
    url: jdbc:mysql://127.0.0.1:3306/imchat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        username: nacos
#        password: nacos
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 12345678
    virtual-host: imchat


zookeeper:
  curator:
    #    host: 192.168.1.121:2181,192.168.1.122:2181,192.168.1.123:2181
    # 单机/集群的ip:port地址
    host: 127.0.0.1:2181
    # 连接超时时间
    connectionTimeoutMs: 30000
    # 会话超时时间
    sessionTimeoutMs: 3000
    # 每次重试的间隔时间
    sleepMsBetweenRetry: 2000
    # 最大重试次数
    maxRetries: 3
    # 命名空间（root根节点名称）
    namespace: imchat