server:
  servlet:
    context-path: /file
  tomcat:
    uri-encoding: UTF-8
    # 不限制请求体大小
    max-swallow-size: -1

spring:
  application:
    name: secret-chat-file
  profiles:
    active: dev   # dev-开发环境; prod-生产环境; test-测试环境;
  servlet:
    multipart:
      max-file-size: 500MB      # 文件上传大小的限制
      max-request-size: 500MB   # 文件最大请求限制

# 日志级别
logging:
  level:
    root: info