server:
  port: 88

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
#      password: wangzh
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        username: nacos
#        password: nacos